apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: gitops-app
        # Image tag is automatically updated by CI pipeline on every push to main
        image: ankacy/gitops-app:ffa5f092ecb8d9be84fa6f8557aa9e60e4e53e63
        ports:
        - containerPort: 3000