apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: gitops-app
        # Image tag is automatically updated by CI pipeline on every push to main
        image: ankacy/gitops-app:7eb7c4eb3b65285a2852a4e680e53406debfd75c
        ports:
        - containerPort: 3000