name: CI Pipeline - Build & Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ankacy/gitops-app:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ankacy/gitops-app:${{ github.sha }}

      - name: Update deployment image
        run: |
          sed -i "s|ankacy/gitops-app:.*|ankacy/gitops-app:${{ github.sha }}|g" k8s/deployment.yaml

      - name: Commit updated manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "update image tag ${{ github.sha }}" || echo "no changes"
          git push